services:
  - type: web
    name: telegram-finance-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn webhook_app:app"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
